// Static image imports are StaticImageData for next/image. next-env.d.ts
// pulls these in too, but it is generated by next dev/build and gitignored,
// so a clean checkout (CI typechecks before building) has only this file.
/// <reference types="next/image-types/global" />
