feature:
  - head-branch: ['^feature/', '^feat/', '^enhancement/']
bug:
  - head-branch: ['^bug/', '^fix/', '^hotfix/']
chore:
  - head-branch: ['^chore/', '^task/']
documentation:
  - head-branch: ['^doc/', '^docs/']
dependencies:
  - changed-files:
    - any-glob-to-any-file: ['package.json', 'package-lock.json', 'pnpm-lock.yaml']
