version: "1"
rules:
  - base: main
    upstream: dev
    reviewers:
      - aamoghS
    assignees:
      - aamoghS
    conflictReviewers:
      - aamoghS

label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict"
