// Registration form constants — nationwide hackathon application

export const SHIRT_SIZES = ["XS", "S", "M", "L", "XL", "XXL"] as const;
export type ShirtSize = (typeof SHIRT_SIZES)[number];

export const DIETARY_OPTIONS = [
  "Vegetarian",
  "Vegan",
  "Gluten-Free",
  "Halal",
  "Kosher",
  "Dairy-Free",
  "Nut-Free",
  "None",
] as const;

export const LEVELS_OF_STUDY = [
  "Freshman",
  "Sophomore",
  "Junior",
  "Senior",
  "Graduate",
  "PhD",
  "Other",
] as const;
export type LevelOfStudy = (typeof LEVELS_OF_STUDY)[number];

export const GENDERS = [
  "Male",
  "Female",
  "Non-binary",
  "Other",
  "Prefer not to say",
] as const;

export const REGISTRATION_STEPS = [
  "Personal Info",
  "Academic Info",
  "Experience",
  "Logistics",
] as const;

/**
 * Instant-render fallback, Atlanta first. The real list is MLH's 12k schools in
 * `public/schools.json`, fetched when the academic step opens. Both are
 * suggestions — the field takes free text.
 */
export const SCHOOLS = [
  "Georgia Institute of Technology",
  "Emory University",
  "Georgia State University",
  "University of Georgia",
  "Kennesaw State University",
  "Morehouse College",
  "Spelman College",
  "Clark Atlanta University",
  "Agnes Scott College",
  "MIT",
  "Stanford University",
  "Harvard University",
  "Carnegie Mellon University",
  "University of California, Berkeley",
  "University of Michigan",
  "University of Illinois Urbana-Champaign",
  "Purdue University",
  "University of Texas at Austin",
  "University of Washington",
  "Columbia University",
  "Cornell University",
  "University of Pennsylvania",
  "Princeton University",
  "Yale University",
  "Duke University",
  "Northwestern University",
  "University of Chicago",
  "California Institute of Technology",
  "Rice University",
  "Vanderbilt University",
  "University of Virginia",
  "University of Florida",
  "University of California, Los Angeles",
  "University of Southern California",
  "New York University",
  "Boston University",
  "Northeastern University",
  "University of Maryland",
  "Virginia Tech",
  "North Carolina State University",
  "University of North Carolina at Chapel Hill",
  "Penn State University",
  "Ohio State University",
  "University of Wisconsin-Madison",
  "University of Minnesota",
  "Arizona State University",
  "University of Colorado Boulder",
  "Texas A&M University",
  "Florida State University",
  "University of Central Florida",
  "Other",
] as const;

/** Suggestions across every field family, not a list of eligible majors. */
export const MAJORS = [
  // Computing and information
  "Computer Science",
  "Computer Engineering",
  "Software Engineering",
  "Data Science",
  "Artificial Intelligence",
  "Machine Learning",
  "Information Systems",
  "Information Technology",
  "Information Science",
  "Cybersecurity",
  "Computational Media",
  "Computational Science",
  "Human-Computer Interaction",
  "Game Design and Development",
  "Web Development",
  "Bioinformatics",
  "Computational Biology",
  "Computational Linguistics",
  "Robotics",
  // Engineering
  "Aerospace Engineering",
  "Agricultural Engineering",
  "Architectural Engineering",
  "Biomedical Engineering",
  "Biological Engineering",
  "Chemical Engineering",
  "Civil Engineering",
  "Construction Management",
  "Electrical Engineering",
  "Engineering Physics",
  "Engineering Management",
  "Environmental Engineering",
  "Industrial Engineering",
  "Materials Science and Engineering",
  "Mechanical Engineering",
  "Mechatronics",
  "Nuclear Engineering",
  "Ocean Engineering",
  "Petroleum Engineering",
  "Systems Engineering",
  "Engineering Technology",
  // Mathematics and physical sciences
  "Mathematics",
  "Applied Mathematics",
  "Statistics",
  "Actuarial Science",
  "Operations Research",
  "Physics",
  "Astronomy",
  "Astrophysics",
  "Chemistry",
  "Biochemistry",
  "Geology",
  "Earth Sciences",
  "Atmospheric Science",
  "Oceanography",
  "Materials Science",
  // Life and health sciences
  "Biology",
  "Molecular Biology",
  "Microbiology",
  "Genetics",
  "Neuroscience",
  "Ecology",
  "Marine Biology",
  "Zoology",
  "Botany",
  "Biotechnology",
  "Pre-Med",
  "Medicine",
  "Nursing",
  "Pharmacy",
  "Dentistry",
  "Veterinary Medicine",
  "Public Health",
  "Epidemiology",
  "Health Informatics",
  "Health Sciences",
  "Nutrition and Dietetics",
  "Kinesiology",
  "Exercise Science",
  "Physical Therapy",
  "Occupational Therapy",
  "Speech-Language Pathology",
  "Athletic Training",
  "Sports Medicine",
  // Business
  "Accounting",
  "Business Administration",
  "Business Analytics",
  "Entrepreneurship",
  "Finance",
  "Human Resources",
  "International Business",
  "Management",
  "Management Information Systems",
  "Marketing",
  "Operations Management",
  "Real Estate",
  "Supply Chain Management",
  "Hospitality Management",
  "Sports Management",
  // Social sciences
  "Anthropology",
  "Archaeology",
  "Criminology",
  "Criminal Justice",
  "Economics",
  "Geography",
  "Global Studies",
  "International Relations",
  "Political Science",
  "Public Policy",
  "Public Administration",
  "Psychology",
  "Cognitive Science",
  "Sociology",
  "Social Work",
  "Urban Planning",
  "Women's and Gender Studies",
  "Ethnic Studies",
  "African American Studies",
  "Asian Studies",
  "Latin American Studies",
  // Humanities
  "American Studies",
  "Classics",
  "Comparative Literature",
  "English",
  "History",
  "Linguistics",
  "Literature",
  "Philosophy",
  "Religious Studies",
  "Theology",
  "Ethics",
  "Foreign Languages",
  "Spanish",
  "French",
  "German",
  "Chinese",
  "Japanese",
  "Arabic",
  // Arts, media and design
  "Architecture",
  "Landscape Architecture",
  "Interior Design",
  "Industrial Design",
  "Product Design",
  "Graphic Design",
  "UX/UI Design",
  "Design",
  "Fashion Design",
  "Animation",
  "Art History",
  "Studio Art",
  "Digital Media",
  "Film and Television",
  "Photography",
  "Music",
  "Music Technology",
  "Theatre",
  "Dance",
  "Creative Writing",
  // Communication and education
  "Advertising",
  "Communications",
  "Journalism",
  "Media Studies",
  "Public Relations",
  "Technical Communication",
  "Education",
  "Early Childhood Education",
  "Elementary Education",
  "Secondary Education",
  "Special Education",
  "Educational Technology",
  "Instructional Design",
  "Library Science",
  // Environment, agriculture and applied fields
  "Agriculture",
  "Agricultural Business",
  "Animal Science",
  "Environmental Science",
  "Environmental Studies",
  "Sustainability",
  "Forestry",
  "Food Science",
  "Horticulture",
  "Wildlife Conservation",
  "Aviation",
  "Aeronautics",
  "Logistics",
  "Law",
  "Pre-Law",
  "Paralegal Studies",
  "Military Science",
  "Homeland Security",
  "Emergency Management",
  "Liberal Arts",
  "General Studies",
  "Interdisciplinary Studies",
  "Undecided",
  "Other",
] as const;
