// Registration form constants — nationwide hackathon application

export const SHIRT_SIZES = ["XS", "S", "M", "L", "XL", "XXL"] as const;
export type ShirtSize = (typeof SHIRT_SIZES)[number];

export const DIETARY_OPTIONS = [
  "Vegetarian",
  "Vegan",
  "Gluten-Free",
  "Halal",
  "Kosher",
  "Dairy-Free",
  "Nut-Free",
  "None",
] as const;

export const LEVELS_OF_STUDY = [
  "Freshman",
  "Sophomore",
  "Junior",
  "Senior",
  "Graduate",
  "PhD",
  "Other",
] as const;
export type LevelOfStudy = (typeof LEVELS_OF_STUDY)[number];

export const GENDERS = [
  "Male",
  "Female",
  "Non-binary",
  "Other",
  "Prefer not to say",
] as const;

export const REGISTRATION_STEPS = [
  "Personal Info",
  "Academic Info",
  "Experience",
  "Logistics",
] as const;

// Top US universities + common entries (searchable combobox will show filtered results)
export const SCHOOLS = [
  "Georgia Institute of Technology",
  "Emory University",
  "Georgia State University",
  "University of Georgia",
  "Kennesaw State University",
  "Morehouse College",
  "Spelman College",
  "Clark Atlanta University",
  "Agnes Scott College",
  "MIT",
  "Stanford University",
  "Harvard University",
  "Carnegie Mellon University",
  "University of California, Berkeley",
  "University of Michigan",
  "University of Illinois Urbana-Champaign",
  "Purdue University",
  "University of Texas at Austin",
  "University of Washington",
  "Columbia University",
  "Cornell University",
  "University of Pennsylvania",
  "Princeton University",
  "Yale University",
  "Duke University",
  "Northwestern University",
  "University of Chicago",
  "California Institute of Technology",
  "Rice University",
  "Vanderbilt University",
  "University of Virginia",
  "University of Florida",
  "University of California, Los Angeles",
  "University of Southern California",
  "New York University",
  "Boston University",
  "Northeastern University",
  "University of Maryland",
  "Virginia Tech",
  "North Carolina State University",
  "University of North Carolina at Chapel Hill",
  "Penn State University",
  "Ohio State University",
  "University of Wisconsin-Madison",
  "University of Minnesota",
  "Arizona State University",
  "University of Colorado Boulder",
  "Texas A&M University",
  "Florida State University",
  "University of Central Florida",
  "Other",
] as const;

export const MAJORS = [
  "Computer Science",
  "Computer Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Software Engineering",
  "Data Science",
  "Information Technology",
  "Cybersecurity",
  "Biomedical Engineering",
  "Chemical Engineering",
  "Civil Engineering",
  "Industrial Engineering",
  "Mathematics",
  "Statistics",
  "Physics",
  "Biology",
  "Chemistry",
  "Business Administration",
  "Finance",
  "Economics",
  "Marketing",
  "Design",
  "Graphic Design",
  "UX/UI Design",
  "Psychology",
  "Neuroscience",
  "Pre-Med",
  "Nursing",
  "Public Health",
  "Environmental Science",
  "Political Science",
  "Communications",
  "Journalism",
  "English",
  "History",
  "Philosophy",
  "Undecided",
  "Other",
] as const;
